<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>js</string>
		<string>htc</string>
		<string>jsx</string>
		<string>compile.js</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)^
			#   Yes *+      Open  (         Blank |Comments                                        | (No Paren | String) | String                                                        | (Nested Parens             )  )*+
			(?&gt; \g&lt;yesS&gt;*+  \[    (?&lt;yesS&gt;  (?!.) |//.*+|/\*((?!\*/).)++(\*/|$)|(^)((?!/\*).)*(\*/)| (?&lt;noS&gt;[^\[\]&apos;&quot;/]) | (?&lt;str&gt; &apos;(\\&apos;|[^&apos;])*+&apos; | &quot;(\\&quot;|[^&quot;])*+&quot; | /(\\/|[^/])*+/) | (?&lt;squar&gt; \[ \g&lt;yesS&gt;*+ \] )  )*+
			|   \g&lt;yesR&gt;*+  \(    (?&lt;yesR&gt;  (?!.) |//.*+|/\*((?!\*/).)++(\*/|$)|(^)((?!/\*).)*(\*/)| (?&lt;noR&gt;[^\(\)&apos;&quot;/]) | \g&lt;str&gt;                                                       | (?&lt;round&gt; \( \g&lt;yesR&gt;*+ \) )  )*+
			|   \g&lt;yesC&gt;*+  \{    (?&lt;yesC&gt;  (?!.) |//.*+|/\*((?!\*/).)++(\*/|$)|(^)((?!/\*).)*(\*/)| (?&lt;noC&gt;[^\{\}&apos;&quot;/]) | \g&lt;str&gt;                                                       | (?&lt;curly&gt; \{ \g&lt;yesC&gt;*+ \} )  )*+
		)$</string>
	<key>foldingStopMarker</key>
	<string>(?x)^
			#                     (         Blank |Comments                                        | (No Paren | String) | String                                                        | (Nested Parens             )  )*+  Close  Yes *+
			(?&gt;                   (?&lt;yesS&gt;  (?!.) |//.*+|/\*((?!\*/).)++(\*/|$)|(^)((?!/\*).)*(\*/)| (?&lt;noS&gt;[^\[\]&apos;&quot;/]) | (?&lt;str&gt; &apos;(\\&apos;|[^&apos;])*+&apos; | &quot;(\\&quot;|[^&quot;])*+&quot; | /(\\/|[^/])*+/) | (?&lt;squar&gt; \[ \g&lt;yesS&gt;*+ \] )  )*+  \]     \g&lt;yesS&gt;*+
			|                     (?&lt;yesR&gt;  (?!.) |//.*+|/\*((?!\*/).)++(\*/|$)|(^)((?!/\*).)*(\*/)| (?&lt;noR&gt;[^\(\)&apos;&quot;/]) | \g&lt;str&gt;                                                       | (?&lt;round&gt; \( \g&lt;yesR&gt;*+ \) )  )*+  \)     \g&lt;yesR&gt;*+
			|                     (?&lt;yesC&gt;  (?!.) |//.*+|/\*((?!\*/).)++(\*/|$)|(^)((?!/\*).)*(\*/)| (?&lt;noC&gt;[^\{\}&apos;&quot;/]) | \g&lt;str&gt;                                                       | (?&lt;curly&gt; \{ \g&lt;yesC&gt;*+ \} )  )*+  \}     \g&lt;yesC&gt;*+
		)$</string>
	<key>name</key>
	<string>JavaScript JSDoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(/\*\*)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.jsdoc</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>pepe.text.html</string>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.jsdoc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.documentation.jsdoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)param)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.param.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.param.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)return)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.return.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.return.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)throws)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.throws.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.throws.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)exception)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.exception.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.exception.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)author)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.author.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.author.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)version)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.version.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.version.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)see)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.see.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.see.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)since)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.since.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.since.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)serial)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.serial.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.serial.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)serialField)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.serialField.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.serialField.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)serialData)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.serialData.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.serialData.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\@)deprecated)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.deprecated.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*\*?\s*@|\*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.deprecated.jsdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.custom.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((\@)\S+)\s</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?if|while|for|return)\s</string>
			<key>name</key>
			<string>comment.block.documentation.jsdocword</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-formatting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((https?|s?ftp|ftps|file|smb|afp|nfs|(x-)?man|gopher|txmt)://|mailto:)[-:@a-zA-Z0-9_.~%+/?=&amp;#]+(?&lt;![.?:])</string>
					<key>name</key>
					<string>markup.underline.link</string>
				</dict>
			</array>
		</dict>
		<key>inline-formatting</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{)((\@)code)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.code.jsdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.raw.code.jsdoc</string>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.jsdoc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.template.code.jsdoc</string>
					<key>patterns</key>
					<array/>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)((\@)literal)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.literal.jsdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.raw.literal.jsdoc</string>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.jsdoc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.template.literal.jsdoc</string>
					<key>patterns</key>
					<array/>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.docRoot.jsdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.jsdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)docRoot)(\})</string>
					<key>name</key>
					<string>meta.tag.template.docRoot.jsdoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.inheritDoc.jsdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.jsdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)inheritDoc)(\})</string>
					<key>name</key>
					<string>meta.tag.template.inheritDoc.jsdoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.link.jsdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.jsdoc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.jsdoc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.jsdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)link)(?:\s+(\S+?))?(?:\s+(.+?))?\s*(\})</string>
					<key>name</key>
					<string>meta.tag.template.link.jsdoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.linkplain.jsdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.linkplain.jsdoc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.jsdoc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.jsdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)linkplain)(?:\s+(\S+?))?(?:\s+(.+?))?\s*(\})</string>
					<key>name</key>
					<string>meta.tag.template.linkplain.jsdoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.jsdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.value.jsdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsdoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.other.jsdoc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.jsdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)value)\s*(\S+?)?\s*(\})</string>
					<key>name</key>
					<string>meta.tag.template.value.jsdoc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.jsdoc</string>
	<key>uuid</key>
	<string>67DD54A8-932D-4CAE-9AB2-7A8C96FD58BF</string>
</dict>
</plist>
